# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 8 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Coolbet # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Coolbet # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DavidDarnes
    - https://github.com/coolbet

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Tallinn # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text:

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Coolbet.Tech" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Tech Blog from Coolbet Tech team" # Site description and default description, also used in jekyll-seo-tag
url: "https://coolbet.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/coolbet/coolbet.github.io "
email: "it@coolbet.com"
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/coolbet_logo@16px.png'
  32: '/assets/logos/coolbet_logo@32px.png'
  96: '/assets/logos/coolbet_logo@96px.png'
  120: '/assets/logos/coolbet_logo@120px.png'
  144: '/assets/logos/coolbet_logo@144px.png'
  180: '/assets/logos/coolbet_logo@180px.png'
  512: '/assets/logos/coolbet_logo@512px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Categories
  url: /categories/
- title: Search
  url: /search/

navigation_footer:
- title: Created with Alembic - Coolbet
  url: https://coolbet.com

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/company/coolbetofficial/
  GitHub: https://github.com/coolbet
  link: https://coolbet.com
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#70c62a"
  facebook: "#17beff"
  Linkedin: "#ff8f04"
  Email: "#e11d00"
